---
title: "PA1_template.Rmd"
author: "Casey645"
date: "January 24, 2016"
output: html_document
---
Reproducible Research: Peer Assessment 1
========================================================
Loading and preprocessing the data

```
unzip('activity.zip')
accel <- read.csv('activity.csv', header=TRUE, sep = ',')
str(accel)
for(i in 1:length(accel) ) {
  str(accel[i])
```
We observe that the date variable is of the type Factor, we therefore recode it as a date variable.

```
accel$date <- as.Date( accel$date, format = '%Y-%m-%d' )
str(accel$date)
```
What is mean total number of steps taken per day?
=========================================================
We start by loading the packages for data manipulation and plotting.

```
library(plyr)
library(ggplot2)
```
We now compute the data needed for the plot.

```
tot.steps <- ddply(accel, .(date),
                  summarize,
                  total.steps = sum(steps)
                  )
head(tot.steps)
```
We can now plot the data.

```
tot.st.plot <- ggplot(tot.steps,
                      aes(x = total.steps)
                      )
tot.st.plot <- tot.st.plot + geom_histogram()
print(tot.st.plot)
```
We now report the summary statistics, to see the mean and median.

```
summary(tot.steps$total.steps)
summary(tot.steps$total.steps)['Mean']
summary(tot.steps$total.steps)['Median']
```
What is the average daily activity pattern?
=======================================================================

Compute the data needed for the plot.

```
av.steps <- ddply(accel, .(interval),
                  summarize,
                  average.steps = mean(steps, na.rm=TRUE
                                       )
                  )
head(av.steps)
```

Plot the computed data.

```
av.st.plot <- ggplot(av.steps,
                     aes(interval, average.steps)
                     )
av.st.plot <- av.st.plot + geom_line()
print(av.st.plot)
```
Find the maximum.

```
summary(av.steps$average.steps)
summary(av.steps$average.steps)['Max.']
```

Imputing missing values
===============================================================================

First we count the rows that have NAs and the ones that do not.

```
table( complete.cases(accel) )
```

Create a new data frame and impute missing values using interval averages.

```
imp.accel <- accel
imp.accel$steps <- ifelse( is.na(imp.accel$steps),
                     av.steps$average.steps[match(imp.accel$interval, av.steps$interval) ],
                     imp.accel$steps )
table( complete.cases(accel) )
table( complete.cases(imp.accel) )
```
```
tot.imp.steps <- ddply(imp.accel, .(date),
                  summarize,
                  total.steps = sum(steps)
                  )
head(tot.imp.steps)
```
We can now plot the data.

```
tot.imp.st.plot <- ggplot(tot.imp.steps,
                      aes(x = total.steps)
                      )
tot.imp.st.plot <- tot.imp.st.plot + geom_histogram()
print(tot.imp.st.plot)
```

We now report the summary statistics, to see the mean and median.

```
summary(tot.imp.steps$total.steps)
summary(tot.imp.steps$total.steps)['Mean']
summary(tot.imp.steps$total.steps)['Median']
```

The results of the imputing of data seem to be that the histogram is now a closer approximation of the Gaussian distribution, the mean and median appear to remain unchanged.

Are there differences in activity patterns between weekdays and weekends?
==================================================================================
First we create a day of the week variable in the accel data frame, then we create a list of weekdays and weekend days.
```
accel$day <- weekdays(accel$date)

w.day <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
w.e.day <- c('Saturday', 'Sunday')

accel$weekpart <- ifelse(accel$day %in% w.day, 'weekday', 'weekend')
head(accel)
table(accel$weekpart)
```
Now computer the data for plotting.
```
av.w.e.steps <- ddply(accel, .(interval, weekpart),
                  summarize,
                  average.steps = mean(steps, na.rm=TRUE
                                       )
                  )
head(av.w.e.steps)
```
Now plot in two facets using this factor variable.
```
av.w.e.st.plot <- ggplot(av.w.e.steps,
                     aes(interval, average.steps)
                     )
av.w.e.st.plot <- av.w.e.st.plot + geom_line()
av.w.e.st.plot <- av.w.e.st.plot + facet_grid(weekpart ~ .)
print(av.w.e.st.plot)
```